# ============================================================================
# PRODUCTION CONFIGURATION
# ============================================================================
# Large-scale production configuration with balanced augmentation
# Optimized for real-world OCR training with realistic documents

dataset:
  total_samples: 100         # Large production dataset
  text_percentage: 85           # 85% text, 15% special chars (OCR best practice)
  output_dir: "dataset"

input:
  text_file: "input/raw_text/text.txt"
  special_file: "input/raw_text/special.txt"

text_processing:
  max_line_length_text: 100
  max_line_length_special: 50

fonts:
  directory: "fonts"
  target_text_height: 32        # Tesseract LSTM optimal
  padding: 10

augmentation:
  enabled: true
  percentage: 40                # Balanced augmentation for production

  rotation:
    enabled: true
    probability: 0.7            # Most scanned docs have slight rotation
    angle_range: [-2, 2]

  noise:
    enabled: true
    probability: 0.5
    level: 0.01

  blur:
    enabled: true
    probability: 0.5
    radius_range: [0.5, 0.8]

  brightness:
    enabled: true
    probability: 0.6
    factor_range: [0.88, 1.12]

  contrast:
    enabled: true
    probability: 0.4
    factor_range: [0.9, 1.1]

background:
  enabled: true
  percentage: 70                # 70% realistic backgrounds (recommended)
  intensity: "medium"           # Best for general-purpose OCR

output:
  format: "tif"
  dpi: 300
  progress_interval: 100        # Progress every 100 images

advanced:
  duplicate_prevention: true
  max_attempts_multiplier: 100
  random_seed: null             # Random for production diversity
  enable_logging: false

